#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Try desktop screen layout, failing that go to laptop
#laptop

# Change your keymap:
xsetroot -cursor_name left_ptr
xmodmap "/home/jammers/.Xmodmap"
# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
setxkbmap -option grp:switch,grp:alt_shift_toggle -layout "us,ru"
setxkbmap -option ctrl:nocaps       # Make Caps Lock a Control key


sleep 1s && trayer --edge top --align right --SetDockType true --SetPartialStrut true  --expand true --width 6 --transparent true --tint 0x000000 --height 22 --monitor primary&

#xloadimage -onroot -center /usr/share/lubuntu/wallpapers/lubuntu-default-wallpaper.png &
WALLPAPER=/usr/share/lubuntu/wallpapers/$USER-wallpaper.png
if [ ! -f $WALLPAPER ]; then
    WALLPAPER=/usr/share/lubuntu/wallpapers/lubuntu-default-wallpaper.png
fi

feh --bg-fill $WALLPAPER

sleep 5s && xscreensaver -nosplash&

sleep 2s && nm-applet&
sleep 2s &&  system-config-printer-applet&
sleep 2s && blueman-applet&
sleep 3s && xfce4-power-manager&
sleep 2s && pnmixer&
#sleep 2s && bluetooth-applet&
#sleep 2s && xfce4-power-manager&

pcmanfm --daemon-mode &
ibus-daemon&


# `gkrellm&
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec xmonad
# or if you want to keep a log:
# exec fluxbox -log "/home/jammers/.fluxbox/log"


~/.screenlayout/laptop_only.sh
