#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xsetroot -cursor_name left_ptr
xmodmap "/home/jammers/.Xmodmap"
# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
setxkbmap -option grp:switch,grp:alt_shit_toggle -layout "us,ru"
setxkbmap -option ctrl:nocaps       # Make Caps Lock a Control key


trayer --edge top --align right --SetDockType true --SetPartialStrut true  --expand true --width 6 --transparent true --tint 0x000000 --height 17&

xloadimage -onroot -center /usr/share/lubuntu/wallpapers/lubuntu-default-wallpaper.png &

sleep 1s && nm-applet&
sleep 1s &&  system-config-printer-applet&
sleep 1s && blueman-applet&
sleep 3s && xfce4-power-manager&
sleep 1s && volumeicon&
#sleep 2s && bluetooth-applet&
#sleep 2s && xfce4-power-manager&

pcmanfm --daemon-mode &
ibus-daemon&

~/.screenlayout/main.sh 



# `gkrellm&
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec xmonad
# or if you want to keep a log:
# exec fluxbox -log "/home/jammers/.fluxbox/log"


